version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FIREBASE_API_KEY=your-firebase-api-key
      - FIREBASE_AUTH_DOMAIN=your-project.firebaseapp.com
      - FIREBASE_DATABASE_URL=https://your-project.firebaseio.com
      - FIREBASE_PROJECT_ID=your-project
      - FIREBASE_STORAGE_BUCKET=your-project.appspot.com
      - FIREBASE_MESSAGING_SENDER_ID=your-sender-id
      - FIREBASE_APP_ID=your-app-id
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
